FROM consol/sakuli-centos-xfce:v1.1.0-beta

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2017-07-05
ENV TZ=Europe/Berlin

## Install a PDF viewer
USER 0
RUN yum install -y libsane-hpaio http://get.code-industry.net/public/master-pdf-editor-4.2.30_qt5.x86_64.rpm \
    && yum clean all \
        && mkdir -p $HOME/.config/Code\ Industry \
        && echo "[General]" > $HOME/.config/Code\ Industry/Master\ PDF\ Editor.conf \
        && echo "check_updates=0" >> $HOME/.config/Code\ Industry/Master\ PDF\ Editor.conf

## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ENV SAKULI_TEST_SUITE=SAKULI_ROOT/bakery
COPY . $SAKULI_ROOT/bakery
RUN $INST_SCRIPTS/set_user_permission.sh $SAKULI_TEST_SUITE
USER 1984