FROM consol/sakuli-centos-xfce:v1.1.0

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2018-06-05
ENV TZ=Europe/Berlin

## Install
USER 0
### INSTALL zip, curl, masterpdf
RUN yum install -y zip curl libsane-hpaio http://get.code-industry.net/public/master-pdf-editor-4.2.63_qt5.x86_64.rpm \
    && yum clean all \
        && mkdir -p $HOME/.config/Code\ Industry \
        && echo "[General]" > $HOME/.config/Code\ Industry/Master\ PDF\ Editor.conf \
        && echo "check_updates=0" >> $HOME/.config/Code\ Industry/Master\ PDF\ Editor.conf

## ADD is only need due to docker-in-docker jenkins can`t currently mount volumens
ENV SAKULI_TEST_SUITE=/headless/sakuli/bakery
COPY . $SAKULI_TEST_SUITE
RUN $INST_SCRIPTS/set_user_permission.sh $SAKULI_TEST_SUITE
USER 1984