FROM consol/sakuli-ubuntu-xfce:v1.1.0-beta
MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2017-07-05
ENV TZ=Europe/Berlin

## Install a PDF viewer
### INSTALL masterpdf
USER 0
RUN apt-get update && apt-get install -y libqt5svg5 libqt5printsupport5\
    && wget -qO- http://get.code-industry.net/public/master-pdf-editor-4.2.30_qt5.amd64.tar.gz | tar xzs -C /headless \
    && ln -s /headless/master-pdf-editor-4/masterpdfeditor4 /usr/bin/masterpdfeditor4 \
    && mkdir -p $HOME/.config/Code\ Industry \
    && echo "[General]\ncheck_updates=0" >> $HOME/.config/Code\ Industry/Master\ PDF\ Editor.conf \
    && apt-get clean -y
USER 1984

COPY . /opt/sakuli-tests


