### Docker Image for omd config
FROM consol/omd-labs-centos-sakuli:dev

MAINTAINER Tobias Schneck "tobias.schneck@consol.de"
ENV REFRESHED_AT 2017-06-13

ENV TZ Europe/Berlin

ADD ansible_dropin /root/ansible_dropin


