//Jenkinsfile (Declarative Pipeline)
stage('build maven artifacts') {
    node('maven') {
        try {
            checkout scm
            sh "mvn -B -s openshift/infrastructur/maven-cd-settings.xml -f bakery-app/worker/pom.xml deploy"
        }
        finally {
            junit 'bakery-app/**/*.xml'
        }
    }
}
stage('build docker images') {
    parallel bakeryweb: {
        node() {
            sh "openshift/bakery-app/create_bakery-web-server.sh build"
        }
    }, bakeryreport: {
        node() {
            sh "openshift/bakery-app/create_bakery-report-server.sh build"
        }
    }, bakeryworker: {
        node() {
            sh "openshift/bakery-app/create_bakery-workers.sh build"
        }
    }
}
stage('Test') {
}
/*

stage('QA') {
    timeout(time: 2, unit: 'DAYS') {
        input message: 'Do you want to deploy into Prod?'
    }
}
stage('Prod') {
        node {
            dir ("${MODULE_PATH}/infra") {
                sh "./create_module_prod.sh"
                sh "./stage_build.sh qa prod";
            }
        }
}
*/

