apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: ci-builds
parameters:
  - name: APP_NAME
    required: true
  - name: STAGE
    required: true
  - name: GIT_URL
    required: true
    value: 'https://github.com/toschneck/openshift-example-bakery-ci-pipeline'
  - name: GIT_BRANCH
    required: true
    value: 'master'
  - name: GIT_PATH
    required: false
    value: ''
  - name: GITHUB_WEBHOOK_SECRET
    description: GitHub trigger secret
    from: '[a-zA-Z0-9]{8}'
    generate: expression
    required: true
  - name: GENERIC_WEBHOOK_SECRET
    description: Generic build trigger secret
    from: '[a-zA-Z0-9]{8}'
    generate: expression
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${APP_NAME}
    labels:
      application: ${APP_NAME}
      stage: dev
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        ref: ${GIT_BRANCH}
        uri: ${GIT_URL}
      contextDir: ${GIT_PATH}
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: "jenkins/Jenkinsfile.${STAGE}"
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    labels:
      application: ${APP_NAME}
      stage: ${STAGE}
    name: ${APP_NAME}
