MODULE_PATH='.'
stage('Build') {
    node {
        checkout scm
        def buildVersion = sh(script: 'git rev-parse --short HEAD | head -c 7', returnStdout: true)
        dir ("${MODULE_PATH}/infra") {
            sh "./create_module_dev.sh"
            sh "./start_build.sh ${buildVersion}"
            sh "./stage_build.sh latest dev";
        }
    }
}
stage('Test') {
    node('maven') {
        echo sh(script:"mvn --version", returnStdout: true)
        checkout scm
        dir ("${MODULE_PATH}") {
            try {
                sh "mvn -s infra/maven-cd-settings.xml -B clean verify jacoco:report"
            }
            finally {
                archive "target/site/jacoco/**/*"
            }

        }
        dir ("${MODULE_PATH}/infra") {
            sh "./create_module_qa.sh"
            sh "./stage_build.sh dev qa";
        }
    }
}
stage('QA') {
    timeout(time: 2, unit: 'DAYS') {
        input message: 'Do you want to deploy into Prod?'
    }
}
stage('Prod') {
        node {
            dir ("${MODULE_PATH}/infra") {
                sh "./create_module_prod.sh"
                sh "./stage_build.sh qa prod";
            }
        }
}

